name: Build and Publish Docker Image to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # 步骤 1: 【最终决定性修复】为整个任务，向系统申请正确的权限
    # 这会赋予下面那个系统内置的 GITHUB_TOKEN 写入容器仓库的能力
    permissions:
      contents: read
      packages: write
    
    steps:
      # 步骤 2: 检出您的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 3: 登录到 GitHub 容器仓库
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # 步骤 4: 【最终奥义】直接使用系统内置的、拥有正确权限的 GITHUB_TOKEN
          password: ${{ secrets.GITHUB_TOKEN }}

      # 步骤 5: 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
