name: Build and Publish Docker Image to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # 【已移除】我们不再需要向系统申请任何权限，因为我们将使用自己的、拥有最高权限的令牌
    # permissions: ... (删除整个 permissions 块)
    
    steps:
      # 步骤 1: 检出您的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 登录到 GitHub 容器仓库
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # 步骤 3: 【最终决定性修复】使用我们自己创建的、拥有绝对权限的 GH_PAT
          password: ${{ secrets.GH_PAT }}

      # 步骤 4: 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
